### ISSUE TITLE
remove propertynames, put these in the "names" of the propertyargs list

### ISSUE THREAD

**Issue by willmorrison1** [kitbenjamin/daRtInput#11]
#current:
# changing the horizontal and vertical cell dimensions and their corresponding groups
propertyNames <- c("Maket.Scene.CellDimensions.x", "Maket.Scene.CellDimensions.z")
groupNames <- c("group1", "group2")

# define the input arguments as a list of vectors
propertyArgs <- list(c(1, 2, 3, 4, 5, 6), c(2, 4, 6))

#proposed:
propertyNames <- c("Maket.Scene.CellDimensions.x", "Maket.Scene.CellDimensions.z")
names(propertyNames) <- c("group1", "group2")
#this way there is one less argument and it is clearer/less prone to user mistakes

**Comment by kitbenjamin** [comment]
Was thinking of sacking off manually defining group all together so would be:
propertyArgs <- list("Maket.Scene.CellDimensions.x" = c(1, 2, 3, 4, 5, 6),
                                "Maket.Scene.CellDimensions.z" = c(2, 4, 6))   ?

**Comment by willmorrison1** [comment]
Yep sounds good
