### ISSUE TITLE
make a script file that, when run, will run a simulation within the sequence

### ISSUE THREAD

**Issue by willmorrison1** [kitbenjamin/daRtInput#6]
In the sequencer, the user can define which parts of DART ("processes") they want to run (sequencer -> process and threads to run), e.g. directions, maket, ... . This info should all be translated to a script file that can be run at a later date (e.g. on part of a cluster of computers). The script file needs to contain lines of code that execute each "process" in order. The "processes" can be run in the "tools" e.g. "directions" is "DART\tools\windows\directions.bat". Therefore, if the user selects "directions" and "maket" to run, the (OS-dependent) script file will contain (here for linux):

#!/bin/sh
C:/Users/.../DART/tools/linux/dart-directions.sh SIMULATIONFOLDER
C:/Users/.../DART/tools/linux/dart-maket.sh SIMULATIONFOLDER

##end script

where SIMULATIONFOLDER is the folder for the given simulation in the sequence of simulations. As the script file contains information on one simulation, there should be be one script file per simulation. These script files can then b easily be pushed to a computer that is part of a cluster of computers (part of another program to be done later).

**Comment by kitbenjamin** [comment]
[cesbio_test2_0.zip](https://github.com/kitbenjamin/daRtInput/files/3524184/cesbio_test2_0.zip)
Is this how the bat files should look for example?
Currently they are being saved in the newly created directory i.e ~DART/user_data/simulations/simName/daRtinput/datetime_or_description/sequenceFile

**Comment by willmorrison1** [comment]
Yep looks good. you don't need the full directory of the simulation e.g. "cesbio/daRtinput/2019_233_08.56/cesbio/cesbio_test2_0" works best instead of "C:/Users/username/DART/user_data/simulations/cesbio/daRtinput/2019_233_08.56/cesbio/cesbio_test2_0". 

So you chose to run "directions" and "phase" you would have the following script:

echo off
START C:/Users/username/DART/tools/windows/dart-directions.bat cesbio/daRtinput/2019_233_08.56/cesbio/cesbio_test2_0

START C:/Users/username/DART/tools/windows/dart-phase.bat cesbio/daRtinput/2019_233_08.56/cesbio/cesbio_test2_0
